FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY ./target/condition_checker-0.0.1-SNAPSHOT.jar /app/condition_checker-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java", "-jar", "condition_checker-0.0.1-SNAPSHOT.jar"]
